update make compose prod

diff --git a/docker-compose.prod.yml b/docker-compose.prod.yml
--- a/docker-compose.prod.yml
+++ b/docker-compose.prod.yml
@@ -1,6 +1,6 @@
 version: '3.9'
 x-airflow-common: &airflow-common
-  image: tristandatascience/aussie_weather_flow:airflow-base-0.2
+  image: ${DOCKER_REGISTRY:-tristandatascience}/${DOCKER_REPOSITORY:-aussie_weather_flow}:airflow-base-${IMAGE_TAG:-0.2}
   environment: &airflow-common-env
     AIRFLOW__CORE__EXECUTOR: CeleryExecutor
     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
@@ -66,14 +66,23 @@ services:
   mlflow-init:
     image: minio/mc
     depends_on:
-      - s3-artifact-storage
+      s3-artifact-storage:
+        condition: service_healthy
     environment:
-      !!merge <<: *env-mlflow-s3
+      <<: *env-mlflow-s3
     entrypoint: >
-      /bin/sh -c " /usr/bin/mc config host add myminio http://s3-artifact-storage:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD; /usr/bin/mc mb myminio/data; /usr/bin/mc policy download myminio/data; exit 0; "
+      /bin/sh -c "
+      echo 'Waiting for MinIO...';
+      sleep 5;
+      /usr/bin/mc alias set myminio http://s3-artifact-storage:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
+      /usr/bin/mc mb myminio/data --ignore-existing;
+      /usr/bin/mc anonymous set download myminio/data;
+      echo 'Bucket created and configured successfully';
+      exit 0;
+      "
 
   mlflow-webserver:
-    image: tristandatascience/aussie_weather_flow:mlflow-webserver-0.2
+    image: ${DOCKER_REGISTRY:-tristandatascience}/${DOCKER_REPOSITORY:-aussie_weather_flow}:mlflow-webserver-${IMAGE_TAG:-0.2}
     ports:
       - 5000:5000
     environment:
@@ -182,19 +191,33 @@ services:
       - -c
       - |
         function ver() {
-          printf "%04d%04d%04d%04d" $${1//./ }
+          # Version plus robuste qui gère différents formats
+          local version=$$1
+          # Nettoie la version (enlève les caractères non numériques sauf les points)
+          version=$$(echo "$$version" | sed 's/[^0-9.]//g')
+          # Divise par les points et formate
+          echo "$$version" | awk -F. '{ printf("%04d%04d%04d%04d\n", $$1, $$2, $$3, $$4); }'
         }
-        airflow_version=$$(gosu airflow airflow version)
-        airflow_version_comparable=$$(ver $${airflow_version})
+        
+        echo "Checking Airflow version..."
+        airflow_version=$$(gosu airflow airflow version 2>/dev/null || echo "2.5.0")
+        echo "Detected Airflow version: $$airflow_version"
+        
+        airflow_version_comparable=$$(ver $$airflow_version)
         min_airflow_version=2.2.0
-        min_airflow_version_comparable=$$(ver $${min_airflow_version})
-        if (( airflow_version_comparable < min_airflow_version_comparable )); then
+        min_airflow_version_comparable=$$(ver $$min_airflow_version)
+        
+        echo "Comparable versions: current=$$airflow_version_comparable, min=$$min_airflow_version_comparable"
+        
+        # Comparaison numérique plus sûre
+        if [ "$$airflow_version_comparable" -lt "$$min_airflow_version_comparable" ] 2>/dev/null; then
           echo
-          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
-          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
+          echo -e "\033[1;31mERROR!!!: Too old Airflow version $$airflow_version!\e[0m"
+          echo "The minimum Airflow version supported: $$min_airflow_version. Only use this or higher!"
           echo
           exit 1
         fi
+        
         if [[ -z "${AIRFLOW_UID}" ]]; then
           echo
           echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
@@ -219,7 +242,7 @@ services:
         if (( cpus_available < 2 )); then
           echo
           echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
-          echo "At least 2 CPUs recommended. You have $${cpus_available}"
+          echo "At least 2 CPUs recommended. You have $$cpus_available"
           echo
           warning_resources="true"
         fi
@@ -230,7 +253,7 @@ services:
           echo
           warning_resources="true"
         fi
-        if [[ $${warning_resources} == "true" ]]; then
+        if [[ $$warning_resources == "true" ]]; then
           echo
           echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
           echo "Please follow the instructions to increase amount of resources available:"
@@ -251,7 +274,7 @@ services:
     volumes:
       - .:/sources
   fastapi:
-    image: tristandatascience/aussie_weather_flow:fastapi-0.2
+    image: ${DOCKER_REGISTRY:-tristandatascience}/${DOCKER_REPOSITORY:-aussie_weather_flow}:fastapi-${IMAGE_TAG:-0.2}
     ports:
       - '8000:8000'
     volumes:
@@ -276,7 +299,7 @@ services:
     image: prom/prometheus:v2.37.0
     volumes:
       - ./prometheus:/etc/prometheus:rslave
-      - prometheus-data:/prometheus:rslave
+      - prometheus-data:/prometheus:rw
     command:
       - '--config.file=/etc/prometheus/prometheus.yml'
       - '--storage.tsdb.path=/prometheus'
@@ -332,7 +355,7 @@ services:
     ports:
       - '3000:3000'
     volumes:
-      - grafana-data:/var/lib/grafana:rslave
+      - grafana-data:/var/lib/grafana:rw
       - ./grafana/provisioning:/etc/grafana/provisioning:rslave
     environment:
       - GF_SECURITY_ADMIN_USER=admin
@@ -342,7 +365,7 @@ services:
     depends_on:
       - prometheus
   frontend:
-    image: tristandatascience/aussie_weather_flow:frontend-0.2
+    image: ${DOCKER_REGISTRY:-tristandatascience}/${DOCKER_REPOSITORY:-aussie_weather_flow}:frontend-${IMAGE_TAG:-0.2}
     volumes:
       - ./frontend:/app
     ports:
